import os

# Twitter internal maven repo that houses artifacts shared internally but not open-sourced
repo(name='internal',
     url='http://artifactory.local.twitter.com/libs-releases-local',
     push_db=os.path.join(os.path.dirname(__file__), 'pushdb', 'publish.properties'))
